version: '2'
services:
  web:
    container_name: web
    build: .
    links:
     - mysql:mysql
    ports:
     - "5000:5000"
    volumes:
     - .:/app

  redis:
    container_name: redis
    image: "redis:alpine"

  mysql:
    container_name: mysql
    restart: always
    image: "mysql:5.7"
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "6603:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: theboi

volumes:
  mysql-data: